<a href="https://colab.research.google.com/github/sayed657/Titanic-Data-Analysis/blob/main/Titanic_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/tested.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
x=df['Age'].mean()
x

np.float64(30.272590361445783)

In [ ]:
df['Age'].fillna(x,inplace=True)
df

/tmp/ipykernel_7415/3596487387.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(x,inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [ ]:
x = df['Cabin'].mode()[0]
x

'B57 B59 B63 B66'

In [ ]:
df['Cabin'].fillna(x,inplace=True)
df

/tmp/ipykernel_7415/3427951113.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(x,inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,B57 B59 B63 B66,C

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,B57 B59 B63 B66,C

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
413    False
414    False
415    False
416    False
417    False
Length: 418, dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,B57 B59 B63 B66,C

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df['Sex'] = df['Sex'].str.lower()

In [ ]:
df['Sex'] = df['Sex'].replace({
    'male':'M',
    'female':'F'
})

In [ ]:
q1 = df['Fare'].quantile(0.25)
q3 = df['Fare'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [ ]:
outliers = df [(df['Fare'] < lower_bound) | (df['Fare'] > upper_bound)]

In [ ]:
outliers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",F,23.00000,1,0,21228,82.2667,B45,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",F,48.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
48,940,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",F,60.00000,0,0,11813,76.2917,D15,C
53,945,1,1,"Fortune, Miss. Ethel Flora",F,28.00000,3,2,19950,263.0000,C23 C25 C27,S
59,951,1,1,"Chaudanson, Miss. Victorine",F,36.00000,0,0,PC 17608,262.3750,B61,C
64,956,0,1,"Ryerson, Master. John Borie",M,13.00000,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
69,961,1,1,"Fortune, Mrs. Mark (Mary McDougald)",F,60.00000,1,4,19950,263.0000,C23 C25 C27,S
74,966,1,1,"Geiger, Miss. Amalie",F,35.00000,0,0,113503,211.5000,C130,C
75,967,0,1,"Keeping, Mr. Edwin",M,32.50000,0,0,113503,211.5000,C132,C
81,973,0,1,"Straus, Mr. Isidor",M,67.00000,1,0,PC 17483,221.7792,C55 C57,S
96,988,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",F,76.00000,1,0,19877,78.8500,C46,S
114,1006,1,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",F,63.00000,1,0,PC 17483,221.7792,C55 C57,S
118,1010,0,1,"Beattie, Mr. Thomson",M,36.00000,0,0,13050,75.2417,C6,C
141,1033,1,1,"Daniels, Miss. Sarah",F,33.00000,0,0,113781,151.5500,B57 B59 B63 B66,S
142,1034,0,1,"Ryerson, Mr. Arthur Larned",M,61.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
150,1042,1,1,"Earnshaw, Mrs. Boulton (Olive Potter)",F,23.00000,0,1,11767,83.1583,C54,C
156,1048,1,1,"Bird, Miss. Ellen",F,29.00000,0,0,PC 17483,221.7792,C97,S
179,1071,1,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",F,64.00000,0,2,PC 17756,83.1583,E45,C
181,1073,0,1,"Compton, Mr. Alexander Taylor Jr",M,37.00000,1,1,PC 17756,83.1583,E52,C
184,1076,1,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",F,27.00000,1,1,PC 17558,247.5208,B58 B60,C
188,1080,1,3,"Sage, Miss. Ada",F,30.27259,8,2,CA. 2343,69.5500,B57 B59 B63 B66,S
196,1088,0,1,"Spedden, Master. Robert Douglas",M,6.00000,0,2,16966,134.5000,E34,C
202,1094,0,1,"Astor, Col. John Jacob",M,47.00000,1,0,PC 17757,227.5250,C62 C64,C
212,1104,0,2,"Deacon, Mr. Percy William",M,17.00000,0,0,S.O.C. 14879,73.5000,B57 B59 B63 B66,S
217,1109,0,1,"Wick, Mr. George Dennick",M,57.00000,1,1,36928,164.8667,B57 B59 B63 B66,S
218,1110,1,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",F,50.00000,1,1,113503,211.5000,C80,C
234,1126,0,1,"Cumings, Mr. John Bradley",M,39.00000,1,0,PC 17599,71.2833,C85,C
236,1128,0,1,"Warren, Mr. Frank Manley",M,64.00000,1,0,110813,75.2500,D37,C
239,1131,1,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",F,48.00000,1,0,PC 17761,106.4250,C86,C
242,1134,0,1,"Spedden, Mr. Frederic Oakley",M,45.00000,1,1,16966,134.5000,E34,C
252,1144,0,1,"Clark, Mr. Walter Miller",M,27.00000,1,0,13508,136.7792,C89,C
270,1162,0,1,"McCaffry, Mr. Thomas Francis",M,46.00000,0,0,13050,75.2417,C6,C
272,1164,1,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",F,26.00000,1,0,13508,136.7792,C89,C
287,1179,0,1,"Snyder, Mr. John Pillsbury",M,24.00000,1,0,21228,82.2667,B45,S
293,1185,0,1,"Dodge, Dr. Washington",M,53.00000,1,1,33638,81.8583,A34,S
306,1198,0,1,"Allison, Mr. Hudson Joshua Creighton",M,30.00000,1,2,113781,151.5500,C22 C26,S
308,1200,0,1,"Hays, Mr. Charles Melville",M,55.00000,1,1,12749,93.5000,B69,S
314,1206,1,1,"White, Mrs. John Stuart (Ella Holmes)",F,55.00000,0,0,PC 17760,135.6333,C32,C
316,1208,0,1,"Spencer, Mr. William Augustus",M,57.00000,1,0,PC 17569,146.5208,B78,C
324,1216,1,1,"Kreuchen, Miss. Emilie",F,39.00000,0,0,24160,211.3375,B57 B59 B63 B66,S
327,1219,0,1,"Rosenshine, Mr. George (Mr George Thorne"")""",M,46.00000,0,0,PC 17585,79.2000,B57 B59 B63 B66,C
342,1234,0,3,"Sage, Mr. John George",M,30.27259,1,9,CA. 2343,69.5500,B57 B59 B63 B66,S
343,1235,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",F,58.00000,0,1,PC 17755,512.3292,B51 B53 B55,C
352,1244,0,2,"Dibden, Mr. William",M,18.00000,0,0,S.O.C. 14879,73.5000,B57 B59 B63 B66,S
360,1252,0,3,"Sage, Master. William Henry",M,14.50000,8,2,CA. 2343,69.5500,B57 B59 B63 B66,S
365,1257,1,3,"Sage, Mrs. John (Annie Bullen)",F,30.27259,1,9,CA. 2343,69.5500,B57 B59 B63 B66,S
371,1263,1,1,"Wilson, Miss. Helen Alice",F,31.00000,0,0,16966,134.5000,E39 E41,C
374,1266,1,1,"Dodge, Mrs. Washington (Ruth Vidaver)",F,54.00000,1,1,33638,81.8583,A34,S
375,1267,1,1,"Bowen, Miss. Grace Scott",F,45.00000,0,0,PC 17608,262.3750,B57 B59 B63 B66,C
390,1282,0,1,"Payne, Mr. Vivian Ponsonby",M,23.00000,0,0,12749,93.5000,B24,S
397,1289,1,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",F,48.00000,1,1,13567,79.2000,B41,C
400,1292,1,1,"Bonnell, Miss. Caroline",F,30.00000,0,0,36928,164.8667,C7,S
407,1299,0,1,"Widener, Mr. George Dunton",M,50.00000,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",F,37.00000,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",F,39.00000,0,0,PC 17758,108.9000,C105,C

In [ ]:
df = df[(df['Fare'] >= lower_bound) & (df['Fare'] <= upper_bound)]

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",M,34.50000,0,0,330911,7.8292,B57 B59 B63 B66,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",F,47.00000,1,0,363272,7.0000,B57 B59 B63 B66,S
2,894,0,2,"Myles, Mr. Thomas Francis",M,62.00000,0,0,240276,9.6875,B57 B59 B63 B66,Q
3,895,0,3,"Wirz, Mr. Albert",M,27.00000,0,0,315154,8.6625,B57 B59 B63 B66,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",F,22.00000,1,1,3101298,12.2875,B57 B59 B63 B66,S
...,...,...,...,...,...,...,...,...,...,...,...,...
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",F,28.00000,0,0,347086,7.7750,B57 B59 B63 B66,S
413,1305,0,3,"Spector, Mr. Woolf",M,30.27259,0,0,A.5. 3236,8.0500,B57 B59 B63 B66,S
415,1307,0,3,"Saether, Mr. Simon Sivertsen",M,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,B57 B59 B63 B66,S
416,1308,0,3,"Ware, Mr. Frederick",M,30.27259,0,0,359309,8.0500,B57 B59 B63 B66,S
417,1309,0,3,"Peter, Master. Michael J",M,30.27259,1,1,2668,22.3583,B57 B59 B63 B66,C